### ISSUE TITLE
formatting: Work out the silly mess with 0x16 and 0x12

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#10]
Try to get clients to agree to do them consistently, or something.

Right now this warning suffices in the [Reverse Color / Italics](http://modern.ircdocs.horse/formatting.html#reverse-color--or-italics) section, but it shouldn't be necessary.

Maybe we don't even need reverse colors, and we can just throw that into the list of characters at the end that we just write off as unusable / we don't recommend touching.

**Comment by DanielOaks** [comment]
This is done now!

**Comment by dequis** [comment]
@DanielOaks out of curiosity, how? Did 0x12 turn out to not be a thing?

**Comment by DanielOaks** [comment]
@dequis yep, not a thing. Specified in early documentation (the docs around tended to do half as 0x12 and half as 0x16, but real-world implementations very clearly decided:
https://defs.ircdocs.horse/info/formatting.html
