### ISSUE TITLE
Connection registration: sending MODE or 221

### ISSUE THREAD

**Issue by emersonveenstra** [ircdocs/modern-irc#104]
Currently the spec says:
> If the user has client modes set on them automatically upon joining the network, the server SHOULD send the client the RPL_UMODEIS (221) reply

However, Solanum, Insp, and Unreal all send a MODE with the user modes, not a 221. Solanum and unreal send `:nick MODE nick +modes` and insp sends `:n!u@h MODE nick +modes`. Maybe the spec should note this?

**Comment by ProgVal** [comment]
Hybrid sends MODE too, and Ergo sends sends RPL_UMODEIS.
