### ISSUE TITLE
JOIN: describe JOIN 0?

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#12]
`JOIN 0` sent by a client usually means part every channel. How widespread is this in servers, and should we be documenting it here?

**Comment by DanielOaks** [comment]
Yeah we probably should. See 46115333a3f5486a5a031e888354444b4dc63fae

**Comment by jwheare** [comment]
That commit is for JOIN 0, did you mean to close this?

**Comment by DanielOaks** [comment]
Hmm, honestly I think I just stuffed up the name/description of this issue honestly. I'll take another look at it later, thanks for giving me a yell about it.

**Comment by DanielOaks** [comment]
Reopening 'til I get a chance to check this out and make sure I've documented the right thing.

**Comment by DanielOaks** [comment]
Yeah I just messed up the name, thanks for the catch!
