### ISSUE TITLE
RPL_BANLIST format differs in reality

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#124]
According to tommy, they saw this format in use on libera:
```
367 <client> <chan> <mask> <banned_by> <banned_at>
```

The [defs list](https://defs.ircdocs.horse/defs/numerics.html#rpl-banlist-367 contains a different definition, so it makes sense to check out different ircds and see what's in more use and maybe mark the one currently on the defs list as deprecated and mark ^ as the current widely-accepted format for this numeric.

**Comment by tommyrot** [comment]
[RPL_EXCEPTLIST (348)](https://defs.ircdocs.horse/defs/numerics.html#rpl-exceptlist-348) seems to follow this alternate pattern as well, adding two (optional) additional parameters on top of the ones specified by RFC 2812, and names them `<who>` and `<set-ts>`.

RPL_INVITELIST (346) may also need updating to the optional extended form, but i haven't been able to verify its usage.
