### ISSUE TITLE
LIST/NAMES: <server> parameter

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#13]
RFC1459 and 2812 both contain the following:
`LIST [<channel>{,<channel>} [<server>]]`

Same thing for `NAMES`

We don't define that `<server>` parameter... this is irritating. Add `<server>` param and go over method for determining if supplied param is `<server>` or elist stuff.

**Comment by progval** [comment]
Does not seem to be implemented by Insp/Unreal/Solanum (probably many others), and the usefulness seems very limited. So let's ignore this.

We can revisit this later if relevant.
