### ISSUE TITLE
Define more numerics as standard

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#14]
We don't currently define these. Probably good to.
- [x] `RPL_ENDOFWHO`
- [ ] `ERR_WASNOSUCHNICK`
- [x] `RPL_CREATIONTIME`
- [x] `RPL_TOPICTIME` -> actually `RPL_TOPICWHOTIME`

**Comment by Lokathor** [comment]
Freenode sends a 250 message about the highest connection count, but it's not listed in the guide.

**Comment by progval** [comment]
Closing this as `ERR_WASNOSUCHNICK` will be defined by #170
