### ISSUE TITLE
GitHub Pages deploy is broken

### ISSUE THREAD

**Issue by emersion** [ircdocs/modern-irc#140]
Broken by this commit: https://github.com/ircdocs/modern-irc/commit/a3e3751364721e2187483fa6686d033600f666a7

GitHub doesn't support custom plugins: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins

cc @DanielOaks @progval

**Comment by progval** [comment]
We don't use gh-pages anymore, only netlify

**Comment by emersion** [comment]
Ah. It seems like netlify doesn't run on master pushes then.

**Comment by DanielOaks** [comment]
Hmm, #114 broke it but that has nothing that changes any code, so it seems like Jekyll might've just fallen over (Kramdown in particular is what seems to be failing).I'll try rebuilding from scratch and all else fails might be worth just updating the bundle or something like that. Will toss the result in here, 2s!

Aside, @progval have I given you access to the modern site on Netlify? if I haven't, wanna drop a netlify username here so I can toss you access?

**Comment by DanielOaks** [comment]
ohhhh we're not on the gh-pages branch anymore. yeah that'd also be the reason why. another 2s.

**Comment by DanielOaks** [comment]
Yeah that fixed it, Netlify was expecting the gh-pages branch. That's why PRs were still building fine :D

**Comment by progval** [comment]
@DanielOaks you haven't.

I'm not sure what my username is, I don't remember netlify asking for one. Try `progval-netlify`?

**Comment by emersion** [comment]
Thanks @DanielOaks, I now see the latest changes on the website!

**Comment by DanielOaks** [comment]
@progval hmm, seems the netlify sites were taken off the open source plan, totally legit because I haven't met their requirements but yeah that means I can't add ya. give me a bit, I'll split out the ircdocs stuff into their own netlify team, re-apply for the open source tier and add you then.
