### ISSUE TITLE
Add missing RFC commands/messages

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#2]
This is a tracker of commands and messages from RFCs that are missing, and should be added.
- [x] `PRIVMSG`
- [x] `NOTICE`
- [x] `MODE`
- [x] `TRACE`
- [x] `INVITE`
- [x] `KICK`
- [x] `LINKS`
- [x] `WHO`
- [x] `WHOIS`
- [x] `WHOWAS`
- [x] `KILL`
- [x] `PING`
- [x] `PONG`
- [x] `ERROR`
- [x] `REHASH`
- [x] `RESTART`
- [x] `WALLOPS`
- [x] `ISON`
- [x] `SQUIT` command

---

There are some others in the RFC that exist (`SUMMON`, `USERS`), but I don't think they have much applicability to servers or networks today. Put them in that section at the end where we list things we don't like or support these days.

**Comment by DanielOaks** [comment]
`PRIVMSG` was started in 7fb6a262f17c94eb5484d2e242949156c8dd70a5, but there are weird target rules that we need to check and specify.

**Comment by DanielOaks** [comment]
`MODE` described in 9eef7809b3871b96677e18c7d86c7ed2252a23c8 , it seems to be accurate to what servers do these days.

**Comment by h4emp3** [comment]
Can `PRIVMSG` and `KILL` be checked off? They are listed on ircdocs.horse ([PRIVMSG](http://modern.ircdocs.horse/index.html#privmsg-message), [KILL](http://modern.ircdocs.horse/index.html#kill-message)).

Is this list exhaustive?

**Comment by DanielOaks** [comment]
Certainly can, I've just checked them off then. This isn't exhaustive, just a rough list of commands that exist in the RFCs that we'll want to specify in here as well – there's also more well-known, currently-unspecified commands in #4.

**Comment by progval** [comment]
Done!
