### ISSUE TITLE
Document the less-absolute-junk parts of CTCP

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#26]
i.e. investigate writing a cut-down CTCP document that should work in the real world.

Should we do this? Seems like CTCP is kinda in the same place that formatting is, a hundred specs of varying ages, all followed to various degrees and most all of them specifying some stuff everyone supports, some stuff some people support, and some stuff almost nobody supports.

**Comment by dequis** [comment]
There's @grawity's https://gist.github.com/grawity/a74722bfbfc3957684e0

**Comment by DanielOaks** [comment]
Nice, that's really interesting. Will definitely dig into that, thanks for linking it.

**Comment by DanielOaks** [comment]
With permission, edited and adapted @grawity's doc into [this doc here](http://modern.ircdocs.horse/ctcp.html). If there are any issues with it or any problems you see, please yell at me either in an issue, a PR, or anywhere else.

Website doc's still fairly early, I'm guessing there's gonna be a few bouts of further editing before I'm totally happy with it.
