### ISSUE TITLE
Add missing numerics

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#3]
There are lots of numerics we need to add.
- [ ] RFC1459 numerics (minus obsolete ones)
- [ ] RFC2812 numerics (minus obsolete ones)
- [ ] Other widely-used, non-conflicting numerics (see [irc-defs](http://defs.ircdocs.horse))
- [ ] IRCv3 numerics

**Comment by DanielOaks** [comment]
I've been adding a decent amount of numerics recently, basically going through the irc-defs list and seeing which ones look okay and are implemented by all of (or at least a majority of, without conflicts,) the big couple of servers.

**Comment by h4emp3** [comment]
@DanielOaks What are your criteria for selecting 'okay' numerics? I would like to help complete the list ;)

**Comment by DanielOaks** [comment]
Hey @h4emp3, thanks! Regarding numerics I tend to document ones that most IRCds implement/send out, and are relatively universal. I think I've got a decent swathe of them, though the `TRACE` numerics I've totally ignored so far.

**Comment by jobe1986** [comment]
ircu still uses ERR_NORECIPIENT (411), ERR_NOTEXTTOSEND (412) and ERR_NONICKNAMEGIVEN (431)

(Was told to comment here about that)

**Comment by progval** [comment]
I don't think it's worth it to mention them. Clients only get those numerics if they violated the spec by not sending enough arguments.

For the same reason, I'm considering dropping this line from #170:

>  If the `<nick>` argument is missing, they SHOULD send a single reply, using either {% numeric ERR_NONICKNAMEGIVEN %} or {% numeric ERR_NEEDMOREPARAMS %}.

even though these replies are more common than ERR_NORECIPIENT/ERR_NOTEXTTOSEND
