### ISSUE TITLE
Specify WHOX

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#30]
Makes sense to do

**Comment by DanielOaks** [comment]
I'm working on this in the [`whox`](https://github.com/ircdocs/modern-irc/tree/whox) branch. Gonna specify it in such a way that it's clear what to support and use based on what you see.

**Comment by progval** [comment]
Closing this, as this was submitted to IRCv3 by @emersion: https://github.com/ircv3/ircv3-specifications/pull/482

**Comment by progval** [comment]
https://ircv3.net/specs/extensions/whox
