### ISSUE TITLE
Clients shouldn't send prefix of :<nick>

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#33]
Simply put, clients shouldn't put prefixes on messages in general. esp. not when it's just their nickname. Just wastes space and makes things a bit more fragile. I should recommend avoiding it.

**Comment by DanielOaks** [comment]
We now tell clients to avoid this thanks to 9023f3a2c31478be5aae5a328815ce94d7d711fd

**Comment by likcoras** [comment]
I think the language could be clearer on this.

Compare the language on RFC 2812
>  Clients SHOULD NOT use a prefix when sending a message; if they use one, the only valid prefix is the registered nickname associated with the client.

to the current
> Clients MAY include a prefix of their nickname on messages they send (after connection registration has been completed). However, I'd avoid doing so [...]

Sending a :<nick> prefix is not "OPTIONAL", it should be "NOT RECOMMENDED" (RFC 2119).

**Comment by DanielOaks** [comment]
True, I'll bring it back to more forceful language here, thanks for pointing it out!

**Comment by progval** [comment]
Looks like it's done here: https://github.com/ircdocs/modern-irc/blame/8fb236197429a834999858bce089d6a6118d833b/index.md#L326

**Comment by SadieCat** [comment]
> If they do include one, the only valid source is the current nickname of the client.

This is specifically what the issue is about as it doesn't match how things are implemented in practise. I think most servers just ignore a prefix if sent by a client.

It should probably be revised to say that clients should not send a prefix and servers should ignore it entirely if sent.

**Comment by progval** [comment]
Good point. Done in GH-120.
