### ISSUE TITLE
formatting: Add hex colour codes

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#37]
Requested on IRC, adding the hex colour codes to the formatting doc would be good. Need to be denoted as not a lot of clients support them iirc

**Comment by DanielOaks** [comment]
https://modern.ircdocs.horse/formatting.html#hex-color

**Comment by xPaw** [comment]
I think it might be worth documenting if 3 char hex colors should be supported or not. Like `#FFF`.
