### ISSUE TITLE
Serve website with HTTPS

### ISSUE THREAD

**Issue by astorije** [ircdocs/modern-irc#38]
As of its future v2.3.0 version, the Help window of The Lounge will now be pointing to http://modern.ircdocs.horse/formatting.html#colors to explain/list colors to users (see https://github.com/thelounge/lounge/pull/1034).

It would be really nice if we could direct our users to an HTTPS version of this site.
I realize this website is served with GitHub Pages which supports both custom domains and HTTPS **but** not at the same time. I am not a sales rep or anything, but I have been using [Netlify](https://www.netlify.com/) (for free) for this exact purpose and HTTPS, HSTS, HTTP/2 and GitHub integration comes for free. It's a 1-click thing like GitHub Pages, nothing to configure.

**Comment by euank** [comment]
To throw my paint on the bikeshed, I've found cloudflare's ssl proxy to be nice for this purpose.

You can still use github pages per normal, and cloudflare's dns is pretty nice regardless. 
ref: https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by DanielOaks** [comment]
I definitely agree that this is cool! I've recently setup Netlify on https://oragono.io/ for HTTPS and it works pretty brilliantly, so I'll try to set that up in the next few days or so.

**Comment by DanielOaks** [comment]
@astorije this should now be done and accessible with https://modern.ircdocs.horse/formatting.html#colors

if not then it should be accessible within 24-48 hours, everything's all setup and successfully configured, nameservers may be cached there for a bit though. Thanks for the push to do this!

**Comment by astorije** [comment]
Sweet, awesome @DanielOaks!
And as a perk you can now set up PRs to build the website for you before merging :)

I think after all that happened to Cloudflare (and even before), I'd more happily give my free money to Netlify than them. I actually created an account for personal purpose on Cloudflare before backing off and going to Netlify :)

Thanks again!
