### ISSUE TITLE
RPL_ISUPPORT links in "Feature Advertisement"

### ISSUE THREAD

**Issue by linuxdaemon** [ircdocs/modern-irc#45]
The RPL_ISUPPORT links [here](http://modern.ircdocs.horse/#feature-advertisement) contain an underscore whereas the actual link does not ('#rpl_isupport-005' vs '#rplisupport-005')

**Comment by DanielOaks** [comment]
Awesome, thanks for the yell with this! I've pushed the fix in 064d292f7b662acdb3622034d96d126443c70e42 (as well as fixing the other links that were broken). A while back Github changed how they generated these links, so it broke these ones as well. But should all work now – feel free to yell if you run into any other trouble!
