### ISSUE TITLE
RPL_TOPICTIME/RPL_TOPICWHOTIME (numeric 333)

### ISSUE THREAD

**Issue by tobbez** [ircdocs/modern-irc#47]
* It's currently listed as `RPL_TOPICTIME` in this document
* The name `RPL_TOPICWHOTIME` seems to be used by most. Notable exceptions are InspIRCd and this document. ~80 hits on google for `RPL_TOPICTIME`, ~2.4k for `RPL_TOPICWHOTIME`
* It seems it originated from ircu as `RPL_TOPICWHOTIME` (according to https://www.alien.net.au/irc/).

In summary, it should likely be renamed to `RPL_TOPICWHOTIME` in the document.

Secondly, the format for this numeric is currently documented as: 
```
"<client> <channel> <nick> <setat>"
```

However, this does not seem to hold for all IRC servers: at least freenode (ircd-seven?) returns a mask (i.e. `nick!user@host`) rather than just a nick for the third argument.

**Comment by DanielOaks** [comment]
Ah, thanks very much for raising this! I'll also look at correcting this in the IRC defs lists, since if it's incorrect here it's likely the same there. I'll have a look 'round and see exactly what's used for that third arg and document it according. Thanks again!

**Comment by tobbez** [comment]
The defs list (assuming you're talking about the one in the `irc-defs` repo, and on http://defs.ircdocs.horse/defs/numerics.html) already has the correct name (`RPL_TOPICWHOTIME`). It even notes "Also known as RPL_TOPICTIME (InspIRCd)".

**Comment by DanielOaks** [comment]
Ah, perfect! Thanks very much for raising this issue, I've corrected this in 4841e6c906e0ae0030be52e4c305fcd07285eec1
