### ISSUE TITLE
Flash/blink

### ISSUE THREAD

**Issue by SoniEx2** [ircdocs/modern-irc#53]
At least EPIC supports flash/blink formatting. I'm not sure if it's enabled by default, but it at least parses it.

Seems to be \x06.

**Comment by DanielOaks** [comment]
Thanks, I'll take a look!

**Comment by dgw** [comment]
I've done several spates of research on this over the last few months and have never been able to find anything about a flash/blink control code for IRC, except in this issue and a couple scattered code references that include `\x06` in lists of control characters to remove. No client I've managed to find actually does anything with this control code.

**Comment by ProgVal** [comment]
I'll close this, for the reason mentioned above. We'll reopen it if/when there's evidence there are relevant implementations out there.

**Comment by rcr** [comment]
It's also possible to just add it. Clients should silently ignore unknown control code characters for security reasons anyways.

**Comment by ProgVal** [comment]
From the [guidelines](https://modern.ircdocs.horse/about.html#guidelines):

> These documents SHOULD NOT describe brand new behaviour, but existing behaviour present in IRC software and/or networks (new extensions are IRCv3’s area).
