### ISSUE TITLE
Hidden text

### ISSUE THREAD

**Issue by SoniEx2** [ircdocs/modern-irc#54]
Hidden text can be done with \x08. Hexchat parses it (but doesn't display it as hidden, opting to strip the formatting instead) from incoming messages. It fully supports hidden text in the theme/plugin system, however.

**Comment by DanielOaks** [comment]
I don't get the point of this. This has no practical use so it can get rooted in my opinion, but thanks for the issue!

**Comment by DanielOaks** [comment]
Eh, I'll investigate and ask HexChat why they have this if they do.

**Comment by SoniEx2** [comment]
`\x08<\x08Soni\x08>\x08\thello there` displays as `Soni|hello there` but can be copied as `<Soni> hello there`. It's quite useful in themes/plugins.

**Comment by euank** [comment]
If it's a local theming thing only, and never actually hits the wire, it doesn't really count as part of the "irc protocol", but rather an implementation detail of a client maybe?

I double checked the behavior of various clients out of curiosity.

Using weechat, I can send '\b' (aka '0x08') characters with the following:

```
/exec -o echo -e "foo\bbar"
```

In weechat, it appears to simply display a space character there ("foo bar").
Irssi displays a control-character thing (![irssi](https://user-images.githubusercontent.com/2147649/31258804-a670fa14-a9f6-11e7-9d2a-b8fd4efcbb28.png))
Hexchat and xchat don't display the character ("foobar")


I think this is all within the realm of normal operation for receiving undisplayable characters, and I don't think any specific note should be made of it in this document.
The interesting behavior you mention appears to only be a client-side detail of hexchats theming implementation.

**Comment by DanielOaks** [comment]
Ah coolcool, in that case it's all good and no need for us to worry about it yeah. Thanks a bunch for taking a good look at this @euank, much appreciated.

**Comment by SoniEx2** [comment]
It "hides" it in the same sense that clients that can't display colors "hide" the color code.

In fact, if you copy the text with formatting, you'll see the character is completely removed.

This implies hexchat is actually parsing it.

**Comment by SoniEx2** [comment]
If hidden text was an actual IRC feature, and not something hexchat just blocks, then things like content warnings would be quite doable on normal IRC.

**Comment by DanielOaks** [comment]
I document stuff that already exists, is sane and is present out there in a decent number of clients. This isn't so I'm not interested in documenting it here, sorry.
