### ISSUE TITLE
Alt 16-98 colours

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#55]
Suggested by JustJanne on IRC, http://m8y.org/tmp/extended_mirc_color_proposal.html seems to be supported by a number of clients. May be good to add this to the specs as well, depending on current client adoption.

**edit:** Along with this, make some new rows in the irc-defs formatting support list, for either this method and for the -16 colour code method and all.

**Comment by ailin-nemui** [comment]
why link to that page instead of the canonical  http://anti.teamidiot.de/static/nei/*/extended_mirc_color_proposal.html

**Comment by DanielOaks** [comment]
Ah, that's just the one that was sent my way first, thanks for the correct link!

**Comment by DanielOaks** [comment]
Done with 3ae6fcc52f0ae6349ec570d50b2decae59dcba05, thanks!
