### ISSUE TITLE
ELIST: substring filtering

### ISSUE THREAD

**Issue by ailin-nemui** [ircdocs/modern-irc#58]
recommend that networks allow searching for channels using `/list #*irc*`, as is supported on Quakenet and Undernet. Document that Freenode unfortunately sends the whole friggin list instead of empty output if you try to search for a channel with `/list *freenode*` and that you have to use their services bot (`/msg alis list *freenode*`) instead

**Comment by progval** [comment]
Already documented, as part of the ELIST numeric: https://modern.ircdocs.horse/#elist-parameter

Looks like Freenode didn't support `M` (which is what you want); but Libera.Chat does now.
