### ISSUE TITLE
Make it very clear that trailing is a regular param

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#63]
Write this part of the spec in such a way that servers and clients cannot misunderstand this.

**Comment by rakiru** [comment]
I'm not sure it can be made too much clearer. It is explicitly stated under the parameter parsing example:

    As the last two examples show, a trailing parameter (a parameter prefixed with ':') is another regular parameter. Once the ':' is stripped, software MUST just treat it as another param.

and again in the grammar section:

    After extracting the parameter list, all parameters are equal, whether matched by <middle> or <trailing>. <trailing> is just a syntactic trick to allow SPACE (0x20) characters within a parameter.

The first line, where the colon is initially explained, though, isn't quite as explicit:

    If the final parameter is prefixed with a colon ':', the prefix is stripped and the rest of the message is treated as the final parameter, no matter what characters it contains.

so perhaps just move the `Once the ':' is stripped, software MUST just treat it as another param.` from the example up to this definition?

**Comment by DanielOaks** [comment]
Yeah pretty much, something like that. Someone just had some confusion around this, so I was thinking of adding some examples if they don't exist already (either here or to the IRCv3 SASL spec) like:

> These two messages are exactly the same:
```
COMMAND param1 param2 param3
COMMAND param1 param2 :param3
```

But yeah. I won't mess with it enough to make the doc unreadable or whatever, just wanna do a quick check over and confirm I'm stating it obviously enough for my liking. Thanks for that possible way, I'll keep that in mind as I go! (not gonna make any decisions yet, only once I have the time to properly look over the spec again)

**Comment by rcr** [comment]
I think an illustrative example of what clients get wrong sometimes is the fact that:
```
PRIVMSG nick :some message text
PRIVMSG nick some message text
```
are equivalent, and parsing can't expect a colon delimiting the final argument

**Comment by ailin-nemui** [comment]
1. split on the first "` :`" into A and B
2. split A at all "` `" into A1, A2,...,An
3. the arguments are : A1,... An, B,

**Comment by ailin-nemui** [comment]
ergo at most one parameter can contain spaces, and it must be the last

**Comment by dequis** [comment]
> I think an illustrative example of what clients get wrong sometimes is the fact that:
> ```
> PRIVMSG nick :some message text
> PRIVMSG nick some message text
> ```
> are equivalent, and parsing can't expect a colon delimiting the final argument

Ugh. This is super cursed. These are **not** equivalent.

`PRIVMSG nick :some message text` parses as `["PRIVMSG", "nick", "some message text"]`

`PRIVMSG nick some message text` parses as `["PRIVMSG", "nick", "some", "message", "text"]`

On the other hand, these are equivalent:

`PRIVMSG nick :message` parses as `["PRIVMSG", "nick", "message"]`

`PRIVMSG nick message` parses as `["PRIVMSG", "nick", "message"]`

But in the other case, a server sending a message with spaces without the colon is a broken server. It would be perfectly legal for a client to show only the third parameter, the word "some".

Of course it's better for clients to gracefully handle broken servers and join all parameters after nick. The few clients i checked seem to do this already, and it's probably worth mentioning in the docs too. I wonder what servers send messages like that.

**Comment by DanielOaks** [comment]
Hmm... I think some illustrative examples would definitely be good.

@rcr in those two examples, the parameters of those messages are:
```
PRIVMSG nick :some message text
    ->   ["nick", "some message text"]
PRIVMSG nick some message text
    ->   ["nick", "some", "message", "text"]
```
Those two aren't equivalent -- the first would result in `<user> some message text` and the second would result in `<user> some`, with `"message"` and `"text"` omitted since they're different parameters.

I'll definitely have a better look at this, see what the easiest and best way to show all these sort of cases would be. Thanks a bunch for the input, much appreciated!

**Comment by DanielOaks** [comment]
@dx jinx

**Comment by ailin-nemui** [comment]
(some clients may contain hacks that display `<nick> some message text` when receiving `PRIVMSG nick some message text`, despite it being it clearly incorrect. for strict conformance, displaying only `<nick> some` or an error due to excessive arguments could be expected )

**Comment by rcr** [comment]
okay, fair, my previous example wasn't a great one, but I've seen both of these in the wild on popular servers:

```
MODE target flags
MODE target :flags
```

Point being that the later has 2 `params`, rather than a `param` and a `trailing`

**Comment by progval** [comment]
Closed by GH-116.
