### ISSUE TITLE
fix TOPIC text

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#66]
fix dis text, it's super wrong

> **&lt;ybden>** dan-: "If the topic of a channel is changed or cleared, every client in that channel will receive either a RPL_TOPIC or RPL_NOTOPIC numeric alerting them to how the topic has changed." [modern docs] is just plain wrong? as far as I can tell, basically everywhere just sends a TOPIC message instead?
> **<@dan->** o
> **<@dan->** yeah that's entirely wrong
> **&lt;ybden>** phew, my sanity
> **<@dan->** thanks for the yell, I'll change that to reflect reality

**Comment by jwheare** [comment]
For extra clarity:

RPL_TOPIC (332): sent on channel join or when querying a channel topic with /topic
RPL_NOTOPIC (331): usually sent only when querying a channel topic
RPL_TOPICWHOTIME/RPL_TOPICINFO (333): usually sent after 332
TOPIC (non-numeric): sent when a topic changes
