### ISSUE TITLE
spec WATCH command

### ISSUE THREAD

**Issue by eeeeeta** [ircdocs/modern-irc#67]
Even though it's not defined in any RFC, the [WATCH](https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#WATCH) command is still in wide use, and is probably worth a mention on the spec.

**Comment by eeeeeta** [comment]
Looks like grawity has already done some spec work on it: https://github.com/grawity/irc-docs/blob/master/client/draft-meglio-irc-watch-00.txt

**Comment by progval** [comment]
#127 mentions it as deprecated, and links to grawity's spec.

I'm open to merging a PR that builds upon that spec (or replaces it with something better); but the current state is good enough IMO, so I'm closing this issue.
