### ISSUE TITLE
USER: empty realnames are disallowed

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#85]
this probably isn't described yet, with the `USER` commands some ircds disallow empty realnames (e.g. `USER d d d :` fails with 461 `Not enough parameters`. see if that's universal and if so then describe it in here

**Comment by ProgVal** [comment]
Looks like this is valid for all IRCds: Bahamut, Hybrid/Chary/Solanum, Ergo, irc2, plexus4, and Unreal!

No I'm kidding, there's an exception, of course. ircu2 defaults to "No Info" as realname.
