### ISSUE TITLE
WHOIS: Keep in mind syntax commonly allowed by servers

### ISSUE THREAD

**Issue by DanielOaks** [ircdocs/modern-irc#9]
Most servers today let you send the nick as the first argument. Keep an eye out when we actually start writing that command up and make sure we define it properly.

**Comment by ailin-nemui** [comment]
the target (1st argument) has been optional. as an extension, first argument would resolve to the "server that the nick in 1st argument is on", which is probably the origin of the /whois $0 $0 alias

**Comment by progval** [comment]
Addressed in #115
