### ISSUE TITLE
background color change only

### ISSUE THREAD

**Issue by kkabrams** [ircdocs/modern-irc#91]
What is the reason for ^C,## to not change only the background color?

**Comment by DanielOaks** [comment]
If I remember correctly, clients didn't widely support that syntax. If you're able to go through the well-known clients and confirm they support this though, that syntax could definitely be added! This is the rough formatting testing table that I used when originally deciding what to include here: https://defs.ircdocs.horse/info/formatting

**Comment by kkabrams** [comment]
so far tested:
irssi 1.0.7-1~deb9u1 works
hexchat 2.14.3 works
WeeChat 2.8 works
irssi 1.2.2-1+b1 does not

I haven't found the commit in irssi that caused it to no longer work. I can include screenshots if anyone wants them.

**Comment by ailin-nemui** [comment]
We evaluated this in https://github.com/irssi/irssi/pull/742 and afaik our (Irssi 1.2) Implementation now matches mIRC

**Comment by DanielOaks** [comment]
oh, #51 is a dupe of this. hmm, yeah this'll definitely be a case of deciding based on what proportion of clients support it, thanks for the link @ailin-nemui!

**Comment by progval** [comment]
Closing this as duplicate of #51
